version: '3.1'

services:
  server:
    image: breccia-relationship-mapper
    container_name: relationship-mapper-server
    build: .
    ports:
      - 8000:8000
    environment:
      DEBUG: ${DJANGO_DEBUG}
      DATABASE_URL: sqlite:////app/db.sqlite3
      SECRET_KEY: ${DJANGO_SECRET_KEY}
    volumes:
      - ./db.sqlite3:/app/db.sqlite3:z
      - static_files:/app/static

  caddy:
    image: caddy:2
    container_name: relationship-mapper-caddy
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:z
      # Caddy serves static files collected by Django
      - static_files:/srv/static:ro
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - server

volumes:
  caddy_data:
  caddy_config:
  static_files:
