version: '3.1'

services:
  server:
    image: mgrove36/breccia-mapper:latest
    build: .
    ports:
      - 8000:8000
    environment:
      DJANGO_DEBUG: ${DEBUG}
    env_file:
      - .env
    volumes:
      - ./db.sqlite3:/app/db.sqlite3:z
      - static_files:/app/static
      - media_files:/app/media

  caddy:
    image: caddy:2
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:z
      # Caddy serves static files collected by Django
      - static_files:/srv/static:ro
      - media_files:/srv/media:ro
      - ./icon-192x192.png:/srv/media/icon-192x192.png:ro
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - server

volumes:
  caddy_data:
  caddy_config:
  static_files:
  media_files:
