---
- hosts: all
  become_user: root
  become_method: sudo
  become: yes

  pre_tasks:
    - name: Check if running under Vagrant
      stat:
        path: /vagrant
      register: vagrant_dir

  roles:
    - database
    - webserver

  vars:
    ansible_python_interpreter: python2
