# Generated by Django 2.2.10 on 2020-02-19 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0002_activity_type_medium'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='series',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='activities', to='activities.ActivitySeries'),
        ),
    ]
