# Generated by Django 2.2.10 on 2020-02-19 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0005_user_one_person'),
        ('activities', '0003_rename_activity_series_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='attendance_list',
            field=models.ManyToManyField(related_name='activities', to='people.Person'),
        ),
    ]
