# Generated by Django 2.2.10 on 2020-02-28 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0004_activity_attendance_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='activityseries',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
