# Generated by Django 2.2.10 on 2020-04-02 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0005_shrink_name_fields_to_255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='attendance_list',
            field=models.ManyToManyField(blank=True, related_name='activities', to='people.Person'),
        ),
    ]
