---
- name: Update system packages
  yum:
    name: '*'
    state: latest

- name: Install system prerequisites
  yum:
    name: '{{ packages }}'
    state: latest
  vars:
    packages:
      - mariadb
      - mariadb-devel
      - mariadb-server
      - python
      # For Ansible - not used at runtime
      - MySQL-python

- name: Restart database server
  service:
    name: mariadb
    state: restarted
    enabled: yes
    daemon_reload: yes

- name: Create database
  mysql_db:
    name: '{{ db_name }}'
    state: present

- name: Create database user
  mysql_user:
    name: '{{ db_user }}'
    password: '{{ db_pass }}'
    state: present
    priv: '{{ db_name }}.*:ALL'
