# Generated by Django 2.2.10 on 2020-02-20 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0005_user_one_person'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='relationshipquestion',
            options={'ordering': ['order', 'text']},
        ),
        migrations.AlterModelOptions(
            name='relationshipquestionchoice',
            options={'ordering': ['order', 'text']},
        ),
        migrations.AddField(
            model_name='relationshipquestion',
            name='order',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='relationshipquestionchoice',
            name='order',
            field=models.SmallIntegerField(default=0),
        ),
    ]
