# Generated by Django 2.2.10 on 2020-02-20 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0007_relationship_question_answers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='relationshipquestionchoice',
            options={'ordering': ['question__order', 'order', 'text']},
        ),
    ]
