# Generated by Django 2.2.10 on 2020-02-25 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0011_person_add_organisation'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='job_title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
