# Generated by Django 2.2.10 on 2020-03-09 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0016_add_answer_set'),
    ]

    operations = [
        migrations.AddField(
            model_name='relationshipanswerset',
            name='replaced_timestamp',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
