# Generated by Django 2.2.10 on 2020-05-28 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0017_answerset_replaced_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='email address'),
        ),
    ]
