# Generated by Django 2.2.10 on 2020-06-24 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0019_remove_person_core_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='organisation_started_date',
            field=models.DateField(null=True, verbose_name='Date started at this organisation'),
        ),
    ]
