# Generated by Django 2.2.10 on 2020-11-27 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0024_remove_age_gender'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='relationship',
            name='unique_relationship',
        ),
        migrations.RenameField(
            model_name='relationship',
            old_name='target',
            new_name='target_person',
        ),
        migrations.AddConstraint(
            model_name='relationship',
            constraint=models.UniqueConstraint(fields=('source', 'target_person'), name='unique_relationship'),
        ),
    ]
