# Generated by Django 2.2.10 on 2020-11-27 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0024_remove_age_gender'),
    ]

    operations = []
