# Generated by Django 2.2.10 on 2020-12-07 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0026_move_static_person_questions'),
    ]

    operations = [
        migrations.AddField(
            model_name='personquestion',
            name='is_multiple_choice',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='relationshipquestion',
            name='is_multiple_choice',
            field=models.BooleanField(default=False),
        ),
    ]
