# Generated by Django 2.2.10 on 2020-12-15 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0027_multiple_choice_questions'),
    ]

    operations = [
        migrations.AddField(
            model_name='personanswerset',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='personanswerset',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
