# Generated by Django 2.2.10 on 2021-01-15 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0028_person_location_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organisation',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
