# Generated by Django 2.2.10 on 2021-01-20 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0030_user_consent_given'),
    ]

    operations = [
        migrations.AddField(
            model_name='personquestion',
            name='allow_free_text',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='relationshipquestion',
            name='allow_free_text',
            field=models.BooleanField(default=False),
        ),
    ]
