# Generated by Django 2.2.10 on 2021-02-08 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0031_question_allow_free_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='personquestion',
            name='answer_is_public',
            field=models.BooleanField(default=True, help_text='Should answers to this question be displayed on profiles?'),
        ),
    ]
