# Generated by Django 2.2.10 on 2021-03-01 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0036_move_latlng_to_answerset'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisationquestion',
            name='filter_text',
            field=models.CharField(blank=True, help_text='Text to be displayed in network filters - 3rd person', max_length=255),
        ),
        migrations.AddField(
            model_name='personquestion',
            name='filter_text',
            field=models.CharField(blank=True, help_text='Text to be displayed in network filters - 3rd person', max_length=255),
        ),
        migrations.AddField(
            model_name='relationshipquestion',
            name='answer_is_public',
            field=models.BooleanField(default=True, help_text='Should answers to this question be considered public?'),
        ),
        migrations.AddField(
            model_name='relationshipquestion',
            name='filter_text',
            field=models.CharField(blank=True, help_text='Text to be displayed in network filters - 3rd person', max_length=255),
        ),
    ]
