# Generated by Django 2.2.10 on 2021-03-01 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0037_alternate_filter_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='personanswerset',
            name='project_started_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='personquestion',
            name='answer_is_public',
            field=models.BooleanField(default=True, help_text='Should answers to this question be considered public?'),
        ),
    ]
