# Generated by Django 2.2.10 on 2021-03-02 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0039_add_organisation_relationship'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='organisation_relationship_targets',
            field=models.ManyToManyField(related_name='relationship_sources', through='people.OrganisationRelationship', to='people.Organisation'),
        ),
    ]
