# Generated by Django 2.2.10 on 2021-03-05 11:53

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0040_person_organisation_relationship_targets'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisationanswerset',
            name='countries',
            field=django_countries.fields.CountryField(blank=True, help_text='Geographical spread - in which countries does this organisation have offices? Select all that apply', max_length=746, multiple=True),
        ),
        migrations.AddField(
            model_name='organisationanswerset',
            name='hq_country',
            field=django_countries.fields.CountryField(blank=True, help_text='In which country does this organisation have its main location?', max_length=2),
        ),
        migrations.AddField(
            model_name='organisationanswerset',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='organisationanswerset',
            name='website',
            field=models.URLField(blank=True, max_length=255),
        ),
    ]
