# Generated by Django 2.2.10 on 2021-03-08 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0041_add_static_org_questions'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisationquestion',
            name='is_hardcoded',
            field=models.BooleanField(default=False, help_text='Only the order field has any effect for a hardcoded question.'),
        ),
        migrations.AddField(
            model_name='organisationrelationshipquestion',
            name='is_hardcoded',
            field=models.BooleanField(default=False, help_text='Only the order field has any effect for a hardcoded question.'),
        ),
        migrations.AddField(
            model_name='personquestion',
            name='is_hardcoded',
            field=models.BooleanField(default=False, help_text='Only the order field has any effect for a hardcoded question.'),
        ),
        migrations.AddField(
            model_name='relationshipquestion',
            name='is_hardcoded',
            field=models.BooleanField(default=False, help_text='Only the order field has any effect for a hardcoded question.'),
        ),
        migrations.AlterField(
            model_name='personanswerset',
            name='job_title',
            field=models.CharField(blank=True, help_text='Contractual job title', max_length=255),
        ),
    ]
