# Generated by Django 2.2.10 on 2021-03-09 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0042_is_hardcoded_questions'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisationanswerset',
            name='is_partner_organisation',
            field=models.BooleanField(default=False),
        ),
    ]
