# Generated by Django 2.2.10 on 2021-03-10 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0044_themes_to_admin_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisationquestion',
            name='help_text',
            field=models.CharField(blank=True, help_text='Additional hint text to be displayed with the question', max_length=255),
        ),
        migrations.AddField(
            model_name='organisationrelationshipquestion',
            name='help_text',
            field=models.CharField(blank=True, help_text='Additional hint text to be displayed with the question', max_length=255),
        ),
        migrations.AddField(
            model_name='personquestion',
            name='help_text',
            field=models.CharField(blank=True, help_text='Additional hint text to be displayed with the question', max_length=255),
        ),
        migrations.AddField(
            model_name='relationshipquestion',
            name='help_text',
            field=models.CharField(blank=True, help_text='Additional hint text to be displayed with the question', max_length=255),
        ),
        migrations.AlterField(
            model_name='organisationquestion',
            name='filter_text',
            field=models.CharField(blank=True, help_text='Alternative text to be displayed in network filters - 3rd person', max_length=255),
        ),
        migrations.AlterField(
            model_name='organisationrelationshipquestion',
            name='filter_text',
            field=models.CharField(blank=True, help_text='Alternative text to be displayed in network filters - 3rd person', max_length=255),
        ),
        migrations.AlterField(
            model_name='personquestion',
            name='filter_text',
            field=models.CharField(blank=True, help_text='Alternative text to be displayed in network filters - 3rd person', max_length=255),
        ),
        migrations.AlterField(
            model_name='relationshipquestion',
            name='filter_text',
            field=models.CharField(blank=True, help_text='Alternative text to be displayed in network filters - 3rd person', max_length=255),
        ),
    ]
