# Generated by Django 2.2.10 on 2021-03-10 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0045_question_help_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='personanswerset',
            name='external_organisations',
            field=models.CharField(blank=True, max_length=1023),
        ),
    ]
