# Generated by Django 2.2.10 on 2021-03-10 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0046_personanswerset_external_organisations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personanswerset',
            name='external_organisations',
        ),
    ]
