# Generated by Django 2.2.10 on 2021-03-19 15:39

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0051_refactor_hardcoded_questions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personanswerset',
            name='nationality',
            field=django_countries.fields.CountryField(blank=True, default=[], max_length=746, multiple=True),
            preserve_default=False,
        ),
    ]
