# Generated by Django 2.2.10 on 2021-05-09 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0052_allow_multiple_nationalities'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organisation',
            options={'ordering': ['name']},
        ),
    ]
