# Generated by Django 2.2.10 on 2022-03-31 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0053_organisation_order_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisationquestionchoice',
            name='is_negative_response',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='organisationrelationshipquestionchoice',
            name='is_negative_response',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='personquestionchoice',
            name='is_negative_response',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='relationshipquestionchoice',
            name='is_negative_response',
            field=models.BooleanField(default=False),
        ),
    ]
